### ISSUE TITLE
Merge perlite and perlite_web into one Image

### ISSUE THREAD

**Issue by secure-77** [secure-77/Perlite#100]
I want to check to build only one docker image for perlite, which includes the php and nginx engine.  Maybe using this repository as template: https://github.com/TrafeX/docker-php-nginx

I will leave this Issue open as poll, please give it a 👍 if you wish to have Perlite in only one Image.

**Comment by jerivl** [comment]
Hi! I've been using the current version of perlite over the past week and I've been loving it so far.

While I agree that some users may benefit from having the combined docker image, I ask that the current php engine image also continue to be maintained as it allows greater flexibility for custom nginx configurations. Perhaps two different images could be hosted on Docker Hub, a combined nginx+fpm image and an image only containing the fpm engine.

**Comment by secure-77** [comment]
Thanks for you feedback!

> Hi! I've been using the current version of perlite over the past week and I've been loving it so far.
> 
> While I agree that some users may benefit from having the combined docker image, I ask that the current php engine image also continue to be maintained as it allows greater flexibility for custom nginx configurations. Perhaps two different images could be hosted on Docker Hub, a combined nginx+fpm image and an image only containing the fpm engine.

This was my initial point why to separate it, but there are some reasons why you want to have only one image, like hosting it on a NAS os etc., but I will leave this Issue open and see how many really need this, then I will decide if I will provide a single image (as addition to the current setup)

**Comment by voltbit** [comment]
I agree with the merge into a single image, however right now the perlite_web was removed from the docker hub as far as I see, so the change was already made?

**Comment by secure-77** [comment]
no, perlite_web was never on docker hub and always build with the first run (via docker compose)

**Comment by rsubr** [comment]
Thanks for this great project. I have been using Perlite without building any local docker images at all, I only use the [official PHP docker Apache Debian](https://hub.docker.com/_/php) image. Here is my simple setup:


My deployment folder contains one docker-compose and two git repos.

```bash
$ ls -1
docker-compose.yaml
Perlite/       # created by: git clone https://github.com/secure-77/Perlite.git
my-obsidian-vault/  # created by: git clone <my obsidian repo>
```

Content of my `docker-compose.yaml`, please change the published domain `notes.example.com` and your Obisidan vault git directory name.

```yaml
# docker-compose for perlite
# change notes.example.com with your FQDN where you want to host
# change "my-obsidian-vault" with the folder name of your obsidian git repo
# this example uses traefik.io to publish this website online

name: notes-example-com

services:
  notes:
    image: php:8-apache
    restart: always
    container_name: notes.example.com

    environment:
      - NOTES_PATH=notes
      - HIDE_FOLDERS=private,internal
      - LINE_BREAKS=true
      - ALLOWED_FILE_LINK_TYPES=pdf
      - DISABLE_POP_HOVER=false
      - SHOW_TOC=false
      - HOME_FILE=README
      - FONT_SIZE=15
      - HTML_SAFE_MODE=true

    volumes:
      - ./Perlite/perlite:/var/www/html
      # replace "my-obsidian-vault" with your obsidian git repo
      - ./my-obsidian-vault:/var/www/html/notes:ro

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.notes.rule=Host(`notes.example.com`)
      - traefik.http.routers.notes.tls=true
      - traefik.http.routers.notes.tls.certresolver=lets-encrypt
```

Use `.htaccess` to prevent direct browsing of the obsidian directory. The Obisidian folder content must be accessed only via Perlite and never served directly. Note that the two `.htaccess` files need to be committed to your obsidian repo.

```bash
$ cat ./my-obsidian-vault/.htaccess
Deny from all
```

```bash
$ cat ./my-obsidian-vault/.obsidian/themes/.htaccess
Allow from all
```

Updating Perlite and Obsidian repo is trivial.

```bash
(cd Perlite && git pull)
(cd my-obsidian-vault && git pull)
```

Thanks again @secure-77 for your great work!

**Comment by secure-77** [comment]
in release [1.5.9](https://github.com/secure-77/Perlite/releases/tag/1.5.9) the nginx:stable image will be used, so you don't need to build a own image any more. However I will stick to two containers for now as this is more common. thx @rsubr for the idea!

**Comment by morthim** [comment]
Hello!

Since this is a PHP project, why not use [FrankenPHP](https://frankenphp.dev/) ?
It's a PHP app server that use Caddy as a web server.

I tried to deploy Perlite with FrankenPHP and it works.

The `compose.yml` I used after I cloned the project in a new folder:
```yaml
services:
  php:
    container_name: perlite
    image: dunglas/frankenphp
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    restart: unless-stopped
    environment:
      - NOTES_PATH=Demo
      - HIDE_FOLDERS=docs,private,trash
      - LINE_BREAKS=true
      - ABSOLUTE_PATHS=false
      - ALLOWED_FILE_LINK_TYPES=pdf,mp4
      - DISABLE_POP_HOVER=false
      - SHOW_TOC=true
      - SHOW_LOCAL_GRAPH=true
      - HOME_FILE=README
      - FONT_SIZE=15
      - HTML_SAFE_MODE=true
      - TEMP_PATH=/tmp
      - SITE_TITLE=Demo
      - SITE_TYPE=article
      - SITE_URL=
      - SITE_IMAGE=
      - SITE_DESC=
      - SITE_NAME=Perlite
      - SITE_TWITTER=https://x.com/
      - SITE_LOGO=perlite.svg
      - SITE_HOMEPAGE=https://perlite.secure77.de/
      - SITE_GITHUB=https://github.com/

      # FrankenPHP
      # Uncomment SERVER_NAME to access via http://HOST_IP instead of https://localhost 
      # (https://frankenphp.dev/docs/#docker and https://caddyserver.com/docs/caddyfile/concepts#addresses)
      #- SERVER_NAME=http://
    volumes:
      - ./perlite:/app/public:ro
```
The `./perlite` folder is [this folder](https://github.com/secure-77/Perlite/tree/main/perlite)

This could resolve the issue of deploying one Docker image instead of two.
What do you think about this solution ?
