### ISSUE TITLE
Unable to Start Perlite

### ISSUE THREAD

**Issue by addicted-ai** [secure-77/Perlite#104]
**Describe the bug**
Unable to start Perlite

```bash
username@system:~/perlite $ sudo docker-compose up
Starting perlite ... done
Starting perlite_web ... done
Attaching to perlite, perlite_web
perlite    | standard_init_linux.go:219: exec user process caused: exec format error
web_1      | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
web_1      | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
web_1      | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
web_1      | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
perlite exited with code 1
web_1      | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
web_1      | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
web_1      | /docker-entrypoint.sh: Configuration complete; ready for start up
web_1      | 2023/09/11 18:00:39 [emerg] 1#1: host not found in upstream "perlite" in /etc/nginx/conf.d/perlite.conf:16
web_1      | nginx: [emerg] host not found in upstream "perlite" in /etc/nginx/conf.d/perlite.conf:16
perlite_web exited with code 1
```

docker-compose file

```
version: "3.3"

services:
  perlite:
    image: sec77/perlite:latest
    container_name: perlite
#    restart: unless-stopped
#    env_file: docker-compose.env
    environment:
      - NOTES_PATH=obsidian
      - HIDE_FOLDERS=docs,private,trash,_resources
      - LINE_BREAKS=true
      - ALLOWED_FILE_LINK_TYPES=pdf
      - DISABLE_POP_HOVER=false
      - SHOW_TOC=false
      - HOME_FILE=README
      - FONT_SIZE=15
      - HTML_SAFE_MODE=true
    volumes:
      - ./Perlite/perlite:/var/www/perlite
      - /home/username/obsidian:/var/www/perlite/obsidian:ro

  web:
    build:
        context: ./Perlite/web
    image: sec77/perlite_web:stable
    container_name: perlite_web
#    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - ./Perlite/perlite:/var/www/perlite
      - /home/username/obsidian:/var/www/perlite/obsidian:ro
    depends_on:
      - perlite
```
