### ISSUE TITLE
Subdirectories don't work

### ISSUE THREAD

**Issue by codergoblin** [secure-77/Perlite#127]
Hi, for some reason no files in subdirectories are listed in the wiki. 

I've got the following file structure:
```
root@vultr:/data/perlite# tree -d
.
└── Sif
    └── Attachments
```
    
However only the files under /data/perlite/Sif are listed 

![image](https://github.com/secure-77/Perlite/assets/72735596/0faadf5f-5c2c-48ed-995b-4d4c33c88728)

If I click attachment nothing comes up an links to it are broken.  

Here's my compose file 

```
root@vultr:/opt/Perlite# cat docker-compose.yml 
version: "3.9"

services:
  perlite:
    image: sec77/perlite:latest
    container_name: perlite
    restart: unless-stopped
    environment:
      - NOTES_PATH=Sif
      - HIDE_FOLDERS=
      - LINE_BREAKS=true
      - ABSOLUTE_PATHES=false
      - ALLOWED_FILE_LINK_TYPES=pdf,mp5,jpeg,jpg,png,bmp
      - DISABLE_POP_HOVER=false
      - SHOW_TOC=true
      - SHOW_LOCAL_GRAPH=true
      - HOME_FILE=README
      - FONT_SIZE=15
      - HTML_SAFE_MODE=true
      - TEMP_PATH=/tmp
      - SITE_TITLE=Storm in phanes
      - SITE_TYPE=article
      - SITE_URL=
      - SITE_IMAGE=
      - SITE_DESC=
      - SITE_NAME=
      - SITE_TWITTER=
      - SITE_LOGO=
      - SITE_HOMEPAGE=
      - SITE_GITHUB=
    volumes:
      - /data/perlite/:/var/www/perlite/Sif/

  web:
    build:
        context: ./web
    image: sec77/perlite_web:stable
    container_name: perlite_web
    restart: unless-stopped
    ports:
      - 80:80
    volumes_from: 
      - perlite       
    depends_on:
      - perlite

```
