### ISSUE TITLE
Docker set up site will not load vault. not many errors

### ISSUE THREAD

**Issue by intrudir** [secure-77/Perlite#154]
**Before creating an Issue**

Is your issue regarding internal links?
no

Is your issue regarding the graph?
no

Is your issue about setup?
yes. docker set up.

**Describe the bug**

**To Reproduce**
1) Edit docker-compose.yml
2) Set NOTES_PATH to obsidian vault path
3) run docker-compose up without -d to see logs live
4) visit http://127.0.0.1:80 and se website does not load. only has outer headers and stuff, no notes

**Expected behavior**
Site should load my notes

docker-compose.yml
```
services:
  perlite:
    image: sec77/perlite:latest
    container_name: perlite
    restart: unless-stopped
    environment:
      - NOTES_PATH=/home/intrudir/InfosecNotes
      - HIDE_FOLDERS=docs,private,trash
      - LINE_BREAKS=true
      - ABSOLUTE_PATHS=false
      - ALLOWED_FILE_LINK_TYPES=pdf,mp4
      - DISABLE_POP_HOVER=false
      - SHOW_TOC=true
      - SHOW_LOCAL_GRAPH=true
      - HOME_FILE=README
      - FONT_SIZE=15
      - HTML_SAFE_MODE=true
      - TEMP_PATH=/tmp
      - SITE_TITLE=Demo
      - SITE_TYPE=article
      - SITE_URL=
      - SITE_IMAGE=
      - SITE_DESC=
      - SITE_NAME=Perlite
      - SITE_TWITTER=https://x.com/
      - SITE_LOGO=perlite.svg
      - SITE_HOMEPAGE=https://perlite.secure77.de/
      - SITE_GITHUB=https://github.com/
    volumes:
      - /home/intrudir/InfosecNotes:/var/www/perlite/InfosecNotes:ro

  web:$
    image: nginx:stable
    container_name: perlite_web
    restart: unless-stopped
    ports:$
      - 80:80
    volumes:
      - ./web/config/perlite.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from: 
      - perlite       
    depends_on:
      - perlite
```

**Screenshots**
When visitng http://127.0.0.1 it complains that the README is missing but it is not. No other errors occur but site wont really load anything
![Image](https://github.com/user-attachments/assets/01cce374-29a9-442c-9cf2-e73cde1387ce)

![Image](https://github.com/user-attachments/assets/bd27c1d3-367c-4e80-bf29-cd4058678df3)

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Browser Brave
 - latest version
