### ISSUE TITLE
Access failed after refreshing the page

### ISSUE THREAD

**Issue by Lasonneil** [secure-77/Perlite#157]
After I installed docker, the access is normal but there is a problem that I can't solve. I hope you can help me solve it. The problem is this:
I visit the web page, the link in the browser is "https://xxx.xxx.site:12345/问题", and I use F12 debugging to find that the request URL is "https://xxx.xxx.site:12345/content.php?mdfile=问题", which can be accessed normally, but once the web page is refreshed, the link in the browser is still "https://xxx.xxx.site:12345/问题", but the web page has shown 404. F12 debugging finds that the request URL is "https://xxx.xxx.site:12345/问题", what is the reason, do I need to modify nginx.conf？Or is there something wrong with my configuration?

docker-compose.yml
```
services:
  perlite:
    image: sec77/perlite:latest
    container_name: perlite
    restart: unless-stopped
    environment:
      - NOTES_PATH=Notes
      - HIDE_FOLDERS=docs,private,trash
      - LINE_BREAKS=true
      - ABSOLUTE_PATHS=false
      - ALLOWED_FILE_LINK_TYPES=pdf,mp4
      - DISABLE_POP_HOVER=false
      - SHOW_TOC=true
      - SHOW_LOCAL_GRAPH=true
      - HOME_FILE=README
      - FONT_SIZE=15
      - HTML_SAFE_MODE=false
      - TEMP_PATH=/tmp
      - SITE_TITLE=Notes
      - SITE_TYPE=article
      - SITE_URL=
      - SITE_IMAGE=
      - SITE_DESC=
      - SITE_NAME=
      - SITE_TWITTER=
      - SITE_LOGO=
      - SITE_HOMEPAGE=
      - SITE_GITHUB=
    volumes:
      - ./data/obsdian/amazon:/var/www/perlite/Notes:ro

  web:
    image: nginx:stable
    container_name: perlite_web
    restart: unless-stopped
    ports:
      - 4980:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - perlite
    depends_on:
      - perlite
```

nginx.conf
```
server {
    listen 80;
    server_name localhost;

    root /var/www/perlite;
    index index.php index.html index.htm;

    access_log /var/log/nginx/php-access.log;
    error_log /var/log/nginx/php-error.log;

    # PHP-FPM Configuration Nginx
    location ~ \.php$ {
        try_files $uri = 404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass perlite:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param REQUEST_URI $request_uri;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

        location ~ /\.ht {
            deny all;
    }

    location ~* ^/(.*)/.obsidian/appearance.json$ {
        allow all;
    }

    location ~* ^/(.*)/.obsidian/(.*)/theme.css$ {
        allow all;
    }

    location ~ \.(git|github|obsidian|trash) {
        deny all;
    }

    location ~ \.(md|json)$ {
        deny all;
    }
}
```
