### ISSUE TITLE
The Docker version cannot start on aarch64 architecture 

### ISSUE THREAD

**Issue by yodahuang** [secure-77/Perlite#33]
**Describe the bug**
The log says
```
exec /usr/local/bin/docker-php-entrypoint: exec format error
```

**To Reproduce**
```
docker compose up
```
Without changing any configurations

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye) aarch64
 - Host: Raspberry Pi 4 Model B Rev 1.1

**Comment by secure-77** [comment]
Hey @yodahuang 

It seems this error is architecture related: https://forums.raspberrypi.com/viewtopic.php?t=335999

unfortunately I don`t have an docker image for arm64. But you can try to build your own. change the docker-compose.yml to the following

```yml
version: "3.9"

services:
  perlite:
    build:
        context: ./perlite
    image: sec77/perlite:latest
    container_name: perlite
    restart: unless-stopped
    environment:
      - NOTES_PATH=Demo
      - HIDE_FOLDERS=docs,private,trash
    volumes:
      - ./Demo:/var/www/perlite/Demo:ro

  web:
    build:
        context: ./web
    image: sec77/perlite_web:stable
    container_name: perlite_web
    restart: unless-stopped
    ports:
      - 80:80
    volumes_from: 
      - perlite       
    depends_on:
      - perlite

```


you may need to delete the downloaded sec77/perlite container and image before.
